### ISSUE TITLE
Small fixes

### ISSUE THREAD

**Issue by niklasniklas** [NFCSKL/NFC-ViAn#167]
Report:
Add a "new line" in report after image and before description, if any. If no description add before filename. OK!

GUI:
Fps to the far right should alwas show the videos fps and not be recalculated with the speed. Also on the form of "25fps" OK!

GUI:
Add video width and height (ex 720x576) to the right of fps. These sholud be changed when rotating.
Example: 25fps (1280x720) or 25fps (720x1280)  OK!

GUI:
Add "Exit button" in "Recent"-dialog. Closes the program. OK!

GUI:
Move buttons { and } to the right of "label" OK!

Menu / GUI:
Change icon for "File->Recent projects..." to House (same as the top-icon in Recent - dialog) OK!
Add "Recent projects"-button in Toolbar OK!

Save:
Add "Auto save" function. After 5 min a question: "You have not saved... Do you wish to save?" Not included!

Drawing:
Drawing while playing shold not be possible. When you start drawing (pressing the left button with a drawingtool) the video should automaitically pause. OK!

Generate report:
Stop playing video when generating report. OK!

Cursor:
Change cursor when zooming in (see file below) (framewidget.cpp, line 494) OK!
Hourglass cursor when generating a report OK!
```
this->setCursor(Qt::WaitCursor);
this->setCursor(Qt::ArrowCursor);

```
Bookmark:
Bookmarkwidget not docked as default. 
Bookmarkwidget opens automatically when the first bookmark is created. OK!

**Comment by niklasniklas** [comment]
Zooming in cursor

![71513-202small](https://user-images.githubusercontent.com/9247462/47048714-86698b00-d19b-11e8-8cb6-94ac4a2c14c4.png)

**Comment by klwing021** [comment]
Drawing: 
Change from "Edit tool" to "Pan/Zoom tool" when you play the video or go to another video/tag/analysis in the project tree.

**Comment by niklasniklas** [comment]
GUI: 
Change toolbar button "open project folder" to: OK!
![open folder](https://user-images.githubusercontent.com/9247462/47386993-63e0f000-d70e-11e8-96c0-d1b354e2ae01.png)

**Comment by henpe071** [comment]
Show rotation

**Comment by niklasniklas** [comment]
Works fine!
