### ISSUE TITLE
"New project" does not clear everything

### ISSUE THREAD

**Issue by niklasniklas** [NFCSKL/NFC-ViAn#175]
* Zoompreview (if you move Zoom preview the frame appears in video widget also)
* Fps: x (in guI)
* No of frames i video
* Zoom % shold be set to 100%

**Comment by henpe071** [comment]
There's some more problems with this. Opening a new project and then resizing the window will cause a crash. If the window is made into a fullscreen the old frame is visible but now it doesn't crash.
