### ISSUE TITLE
Race condition when loading video with set state

### ISSUE THREAD

**Issue by fredrikiselius** [NFCSKL/NFC-ViAn#70]
If the thread handling the playback takes a while to load a new video then the state will be set in the processing thread first which will then be defaulted on load completion. This results improper loading when clicking on a image in an image sequence among other things..

**Comment by henpe071** [comment]
Known issue, the set state call in the video widget is the problem. Don't want to wait in the gui thread before calling set state. Not sure how to best solve this issue.

**Comment by fredrikiselius** [comment]
My initial thought was to introduce additional variables that are read by the frame processor when the new video has been loaded. We would use them instead of the ones used in the set state function. What do you think about that?

**Comment by henpe071** [comment]
Might work, but the set state function is used not only when a new video is loaded but also when changing between tags. So you have to be able to set the state without having to reload the video.
